# Generated by Django 4.2.20 on 2025-04-13 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_scan_scancomment_profile_patientdoctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdoctor',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_links', to='hello.profile'),
        ),
    ]
