# Generated by Django 4.2.20 on 2025-04-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_alter_patientdoctor_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='scan_type',
            field=models.CharField(choices=[('X-Ray', 'X-Ray'), ('CT', 'CT Scan'), ('MRI', 'MRI'), ('Ultrasound', 'Ultrasound'), ('PET', 'PET Scan'), ('ECG', 'ECG'), ('Other', 'Other')], max_length=50),
        ),
    ]
