# Generated by Django 4.2.20 on 2025-04-18 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_alter_scan_scan_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scancomment',
            old_name='doctor',
            new_name='author',
        ),
    ]
