# Generated by Django 4.2.20 on 2025-05-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_doctorinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorinfo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
