# Generated by Django 4.2.20 on 2025-05-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorinfo',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
