# Generated by Django 4.2.20 on 2025-05-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0009_alter_doctorinfo_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorinfo',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctorinfo',
            name='home_address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorinfo',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='doctorinfo',
            name='social_security_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
